### ISSUE TITLE
Build fails because `Error: Unexpected CI service`

### ISSUE THREAD

**Issue by pgoelz** [retorquere/zotero-better-bibtex#1080]
- [X] I have verified in the Zotero addons screen that I have the latest release of BBT (https://github.com/retorquere/zotero-better-bibtex/releases/latest) and Zotero installed
- [X] I am posting a single question, bug or feature request
- [X] I have included a descriptive subject of the problem
- [X] I am available for follow-up questions and testing
- [x] If I am posting an export or key-generation related bug report, I have included an error-report by selecting the problematic reference(s), right-clicking, and submitting an BBT error report from that popup menu

I tried to build the plugin from source as indicated in the [contributing guidelines](https://github.com/retorquere/zotero-better-bibtex/blob/master/CONTRIBUTING.md). `npm install` succeeds, but `npm run build` fails in the stage “copying assets” with the following exception:

> /Users/pgoelz/Documents/programming/zotero-better-bibtex/node_modules/zotero-plugin/continuous-integration.js:43
                throw new Error(`Unexpected CI service ${this.service}`);
                      ^
Error: Unexpected CI service
    at new ContinuousIntegrationSingleton (/Users/pgoelz/Documents/programming/zotero-better-bibtex/node_modules/zotero-plugin/continuous-integration.js:43:23)
    at Object.<anonymous> (/Users/pgoelz/Documents/programming/zotero-better-bibtex/node_modules/zotero-plugin/continuous-integration.js:53:33)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/pgoelz/Documents/programming/zotero-better-bibtex/node_modules/zotero-plugin/version.js:8:34)

The full output of the command can be found here: [betterbibtex.log](https://github.com/retorquere/zotero-better-bibtex/files/2568726/betterbibtex.log). I am running MacOS 10.12, and npm is on version 6.4.1.

It seems that the plugin mistakes my system for a CI one. Should I set any environment variables?

**Comment by retorquere** [comment]
Try getting the latest master from github and run `npm install` to update dependencies.

**Comment by pgoelz** [comment]
That solved the problem; I was able to build the xpi’s. Do you want me to test them? Is there a good way to switch between self-built and release versions in zotero?

**Comment by pgoelz** [comment]
Thanks!

**Comment by retorquere** [comment]
I've already added a test for #1079, but yes, there is a good way to switch between self-built and release versions. If you start zotero with the `-P` switch it will pop up a window that allows you to make a new profile; each profile has its own extensions, and as long as you launch with `-P` you can switch easily (or you can do `-P <profilename>` to immediately launch with that profile.

These profiles will however share your zotero data directory; if you don't want that, you can launch Zotero with `-P -datadir profile` and it will store the Zotero data for that profile inside the profile instead of `$HOME/Zotero`. This doesn't "stick" though so you have to always launch with `-datadir profile` for that profile.

If you are on Linux or MacOS, you can run `npm start`, and that will create a new profile `BBTZ5TEST`, a Zotero datadirectory `$HOME/.BBTZ5TEST`, and will log all output to `$HOME/.BBTZ5TEST.log`. You can launch this profile afterwards with `-P BBTZ5TEST` and that datadir will stick to `$HOME/.BBTZ5TEST`; running `npm start` again will also do the trick but will clean out and re-fill `$HOME/.BBTZ5TEST`, so it's really only useful for testing. What it actually does is start the automated tests, but runs zero tests, and doesn't kill Zotero when those zero tests are done.

**Comment by pgoelz** [comment]
That is great to know! Thanks again for the help!
